In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


Introduction to Tensor

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.item() #getting scalar back as an int

7

In [ ]:
# vector
vector = torch.tensor([7, 6])
vector
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [1, 0]])

MATRIX

tensor([[7, 8],
        [1, 0]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [1, 0, 1],
                        [1, 0 , 1]],
                      [[1, 0, 1],
                       [1, 0 , 0],
                       [0, 0, 1]]])

TENSOR

tensor([[[1, 2, 3],
         [1, 0, 1],
         [1, 0, 1]],

        [[1, 0, 1],
         [1, 0, 0],
         [0, 0, 1]]])

In [ ]:
TENSOR.shape




torch.Size([2, 3, 3])

### Random Tensors
Neural networks learn by starting with tensors full of random number and then adjust those numbers


In [ ]:
random_tensor = torch.rand(1, 3, 3)
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
# Zeros and ones
zero = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3,3))
ones


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Creating a range of tensors and tensors like
odd_to_ten = torch.arange(start=0, end=11, step=2)

In [ ]:
# tensor-like
zero_odd = torch.zeros_like(input=odd_to_ten)
zero_odd

tensor([0, 0, 0, 0, 0, 0])

In [ ]:
# Tensor DataTypes
#float32 tensor
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

1. Tensor not right data type
2. Tensor not right shape
3. Tensor not right device

In [ ]:
float32_tensor.device

device(type='cpu')

# Manipulating Tensors

In [ ]:
tensor = torch.tensor([1, 0, 3])
tensor + 10
tensor * 10
tensor - 10

tensor([ -9, -10,  -7])

In [ ]:
# Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(10)

In [ ]:
tensorA = torch.tensor([[1, 2],
                        [1, 3],
                        [2, 4]])

tensorB = torch.tensor([[2, 3],
                        [5, 5],
                        [2, 7]])

torch.matmul(tensorA, tensorB.T)

tensor([[ 8, 15, 16],
        [11, 20, 23],
        [16, 30, 32]])

In [ ]:
tensorB.T

tensor([[2, 5, 2],
        [3, 5, 7]])

In [ ]:
x = torch.arange(0, 100, 10)
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_extradim = x.reshape(9, 1)
x_extradim, x_extradim.shape

#Change the view
z = x.view(9, 1)
x, z, z.shape, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 torch.Size([9]))

In [ ]:
#Stacking Tensor on top of each other
x_stacked = torch.stack([z, z, z, z], dim=-1
                        )
x_stacked

tensor([[[1., 1., 1., 1.]],

        [[2., 2., 2., 2.]],

        [[3., 3., 3., 3.]],

        [[4., 4., 4., 4.]],

        [[5., 5., 5., 5.]],

        [[6., 6., 6., 6.]],

        [[7., 7., 7., 7.]],

        [[8., 8., 8., 8.]],

        [[9., 9., 9., 9.]]])

In [ ]:
#squeeze

x_squeeze = x_extradim.squeeze()


x_extradim, x_squeeze, x_extradim.shape, x_squeeze.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9, 1]),
 torch.Size([9]))

In [ ]:
# torch.permute - returns a view of the input with its dim's permuted
x_original = torch.rand(size=(224, 224, 3)) #height, width, color channel

x_permute = x_original.permute(2, 0, 1)
x_permute.shape, x_original.shape



(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

### Indexing data

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0] # index the tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] # index dim 1

tensor([1, 2, 3])

In [ ]:
x[0][2][2] #index last dimension

tensor(9)

In [ ]:
# select all of a target dimension
x[:, 2]

tensor([[7, 8, 9]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on X to return 9
# Index on X to return [3, 6, 9]
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:, 2, 2] # to return 9

tensor([9])

In [ ]:
x[0, :, 2] # to return 3, 6, 9

tensor([3, 6, 9])

# PyTorch tensor & Numpy

In [7]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array.dtype, tensor.dtype


(dtype('int64'), torch.int64)

# Reproducibilty - trying to take random out of random

`start with random num -> tensor operations -> update random number`

`torch.rand(3, 3)`

Getting different random numbers each time

To reduce the randomness - random seed

In [12]:
import torch

tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A, tensor_B, sep="\n")
print(tensor_A == tensor_B, sep="\n")

tensor([[0.7617, 0.8368, 0.1403, 0.7006],
        [0.9222, 0.7603, 0.2012, 0.5230],
        [0.3290, 0.1865, 0.0355, 0.3851]])
tensor([[0.9071, 0.9168, 0.1469, 0.5911],
        [0.6216, 0.2954, 0.6619, 0.4717],
        [0.4835, 0.3240, 0.2132, 0.7324]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [14]:
# Random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C, random_tensor_D, sep="\n")
print(random_tensor_C == random_tensor_D, sep="\n")

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Runing Tensor and PyTorch objects on the GPU's

*GPU = faster computation on numbers*

# Getting a GPU

1. Google Colab - for a free GPU
2. Use ur own GPU
3. Use cloud computing

In [1]:
!nvidia-smi

Tue Jun 17 07:09:38 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# Check for GPU access
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

# Putting tensors/models on the GPU


In [9]:
# Create a Tensor( default is on CPU)
tensor = torch.tensor([1, 2, 4])

print(tensor, tensor.device)

tensor([1, 2, 4]) cpu


In [10]:
# Move tensor to GPU if available

tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 4], device='cuda:0')

# Moving tensor back to CPU

In [12]:
# Numpy works with Tensors on the CPU

tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 4])